language: python
sudo: false

# We don't care about Travis' python versions, we install conda anyway
env:
  - CONDA_PYTHON_VERSION=3.5
  - AWS_DEFAULT_REGION=eu-west-1

before_install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

install:
  # Install dependencies
  - conda create --yes -n testenv_$CONDA_PYTHON_VERSION python=$CONDA_PYTHON_VERSION 
  - source activate testenv_$CONDA_PYTHON_VERSION
  - conda install -c https://conda.anaconda.org/babbel boto3 pytest pytest-mock pytest-pythonpath

script:
  - py.test -vv -r sxX

notifications:
  email: true
