language: python
sudo: false

python:
- 3.5

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create --yes -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - source activate test-environment
  - conda install -c https://conda.anaconda.org/babbel boto3 pytest pytest-mock pytest-pythonpath

script:
  - py.test -vv -r sxX

notifications:
  email: true
